stages:
  - build

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  CASSANDRA_CLUSTER_NAME: cassandra-pelops
  CASSANDRA_MAX_HEAP_SIZE: 512m

image: maven

services:
  - name: cassandra:2.1
    alias: cassandra

build:
  stage: build
  script:
    - env
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml