stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  CASSANDRA_HOST: cassandra
  CASSANDRA_THRIFT_PORT: 9160
  CASSANDRA_CLUSTER_NAME: cassandra-pelops
  CASSANDRA_MAX_HEAP_SIZE: 512m

cache:
  paths:
    - .m2/repository/
    - target/

image: maven:3-jdk-8

before_script:
  - if [ -n "$CI_COMMIT_TAG" ]; then
      export VERSIONING_GIT_TAG=$CI_COMMIT_TAG;
    else
      export VERSIONING_GIT_BRANCH=$CI_COMMIT_REF_NAME;
    fi

build:
  stage: build
  services:
    - name: cassandra:2.1
      alias: cassandra
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS -Dmaven.test.skip=true deploy
  artifacts:
    paths:
      - target/*.jar